Liquidation calcUnitsSold tests
lions-mane/tracer-protocol pull request #127
Opened 2021-05-31 00:23 UTC by BenjaminPatch

### Motivation
Tests for liquidation need to be started

### Changes
-

2021-05-31 06:46 UTC, dospore approved these changes

2021-06-01 06:05 UTC, raymogg approved these changes

2021-06-01 06:05 UTC, dospore requested changes
Change it

2021-06-01 06:17 UTC, dospore approved these changes

2021-06-01 06:43 UTC, merged