Fast Gas Price Oracle for Liquidation.sol
lions-mane/tracer-protocol pull request #140
Opened 2021-06-10 07:04 UTC by kumar-ish

### Motivation 

There was previously a mismatch in the perpetual swaps contract with regards to what the gas oracle returned. This has now been fixed, and a fast gas oracle is now passed as a parameter to `Liquidation.sol` so that it can get the fast price of gas (instead of a $ amount previously)

### Changes

- Add fast gas oracle
- Make gas oracle uses consistent

2021-06-10 07:13 UTC, BenjaminPatch requested changes

2021-06-10 07:13 UTC, BenjaminPatch commented on contracts/oracle/FastGasOracle.sol
> +contract FastGasOracle is IOracle, Ownable {
You don't need to make a new contract for this. You can just use `contracts/oracle/Oracle.sol`, which is already done here: https://github.com/tracer-protocol/tracer-protocol/blob/contracts-v2/deploy/FullDeployTest.js#L55

2021-06-10 07:13 UTC, BenjaminPatch commented on deploy/FullDeployTest.js
> +
As per the above comment, https://github.com/tracer-protocol/tracer-protocol/blob/contracts-v2/deploy/FullDeployTest.js#L55 already deploys a gas oracle

2021-06-10 23:53 UTC, BenjaminPatch requested changes

2021-06-10 23:53 UTC, BenjaminPatch commented on deploy/FullDeployTest.js
> +        gasPriceOracle.address,
```suggestion
        gasOracle.address,
```

Since `gasPriceOracle` is the quoteToken/gas oracle.

2021-06-11 04:39 UTC, kumar-ish commented
CI isn't running on this since I goofed it and am merging from the branch on my repo. I think it would be better to merge this a non-(contracts-v2) branch in tracer-protocol/tracer-protocol, then open another PR from that to contracts-v2

2021-06-15 06:09 UTC, kumar-ish commented
Redone with #147

2021-06-15 06:09 UTC, closed without merging