C4: Check ERC20 transfer return value
lions-mane/tracer-protocol pull request #187
Opened 2021-07-12 02:34 UTC by OsmanBran

# Motivation
Address vulnerability identified by Code Arena Audit [Issue 115](https://github.com/code-423n4/2021-06-tracer-findings/issues/115).

The transfer and transferFrom functions from the ERC20 contract are used, however the return values of these functions are not checked.

# Changes
Wrapped calls to these functions inside a require() to check if the return value is true (transfer was successful).

2021-07-13 00:26 UTC, kumar-ish requested changes
As an aside, there's some gas savings with having `require` statements' messages be 32 bytes (characters) or less; see #159

2021-07-13 00:26 UTC, kumar-ish commented on contracts/Insurance.sol
> +        require(collateralToken.transferFrom(msg.sender, address(this), rawTokenAmount), "transfer failed");
It would be good to have a more informative error message; if you look at the other `require` statements in the contracts, they're (I think all) prefixed with a shorthand for the contract.

2021-07-13 00:26 UTC, kumar-ish commented on contracts/TracerPerpetualSwaps.sol
> +        require(IERC20(tracerQuoteToken).transferFrom(msg.sender, address(this), rawTokenAmount), "transfer failed");
Likewise with the perp swaps contract

2021-07-21 06:12 UTC, BenjaminPatch approved these changes

2021-07-21 06:12 UTC, BenjaminPatch commented
lint

2021-07-21 06:15 UTC, kumar-ish approved these changes
Lint && lgtm

2021-07-21 22:07 UTC, merged