Use tracer utils
lions-mane/tracer-protocol pull request #20
Opened 2021-03-19 01:47 UTC by dospore

- Abstract some of the signing logic out so it can be used elsewhere
- Import signing logic from tracer-utils

2021-04-12 03:27 UTC, sporejack requested changes
LGTM -- minor changes though.

2021-04-12 03:27 UTC, sporejack commented on migrations-ts/2_deploy_contracts.ts
> +	'trader': trader
Indentation.

2021-04-12 03:27 UTC, sporejack commented on package.json
> +  "version": "0.0.1",
Should probably reach consensus on versioning here.

2021-06-14 01:33 UTC, closed without merging

2021-06-14 01:33 UTC, raymogg commented
Closed due to inactivity. We can use `tracer-utils` at another point.