LibBalance C4 changes
lions-mane/tracer-protocol pull request #203
Opened 2021-07-18 22:30 UTC by OsmanBran

# Motivation
Addresses code-423n4/2021-06-tracer-findings#118
Addresses code-423n4/2021-06-tracer-findings#116

# Changes
- Removed unnecessary type cast in wadToToken, both values were uint256
- Added decimal checks to ensure maximum of 18 decimals is enforced

2021-07-18 23:31 UTC, BenjaminPatch requested changes

2021-07-18 23:31 UTC, BenjaminPatch commented on contracts/lib/LibBalances.sol
> +        require(tokenDecimals <= 18, "Max decimals exceeded");
```suggestion
        require(tokenDecimals <= MAX_DECIMALS, "Max decimals exceeded");
```

2021-07-18 23:31 UTC, BenjaminPatch commented on contracts/lib/LibBalances.sol
> +        require(tokenDecimals <= 18, "Max decimals exceeded");
```suggestion
        require(tokenDecimals <= MAX_DECIMALS, "Max decimals exceeded");
```

2021-07-18 23:36 UTC, kumar-ish requested changes

2021-07-18 23:36 UTC, kumar-ish commented on contracts/lib/LibBalances.sol
>          uint256 scaler = uint256(10**(MAX_DECIMALS - tokenDecimals));
This cast is unnecessary as well

2021-07-18 23:36 UTC, kumar-ish commented on contracts/lib/LibBalances.sol
>          uint256 scaler = uint256(10**(MAX_DECIMALS - tokenDecimals));
(I think)

2021-07-19 00:01 UTC, BenjaminPatch approved these changes

2021-07-19 00:02 UTC, kumar-ish approved these changes
🎎

2021-07-19 00:13 UTC, merged